### PR TITLE
Issue #52 Change the working directory of the distributed CircleCI job

### PR DESCRIPTION
**Pull request by byrond**
Issue #52 resolved the working directory change for the `drupal8ci` repo, but we saw the same issue with a project created with the distributed CircleCI config. This makes the same change to that file.

### CODE REVIEW

**Review by m4olivei — CHANGES_REQUESTED** [review]
Thanks for this @byrond! While we're at it, could you also correct that path for the `behat.yml` file?

https://github.com/Lullabot/drupal8ci/blob/master/dist/circleci/.circleci/config/behat.yml#L27

As well as phpunit?

https://github.com/Lullabot/drupal8ci/blob/master/dist/circleci/.circleci/config/phpunit.xml#L31
https://github.com/Lullabot/drupal8ci/blob/master/dist/circleci/.circleci/config/phpunit-drupal-8.5.xml#L31

**Comment by byrond** [comment]
You're welcome, @m4olivei! I'll update those now.

**Review by m4olivei — APPROVED** [review]
Looks great! Thanks.

**Comment by byrond** [comment]
@m4olivei would the new Docker image affect Travis and GitLab? There are a few other instances of that path in this repo:
https://github.com/Lullabot/drupal8ci/search?q=%22%2Fvar%2Fwww%2Fhtml%22

**Comment by m4olivei** [comment]
@byrond @juampynr Would be able to speak to that better than me. I suspect that would be the case, yeah. I've only used this in conjunction with CircleCI, so I can only speak for CirclCI.

**Comment by juampynr** [comment]
@byrond @m4olivei Totally, I think that replacing those paths like you point out in your link, @byrond, should fix it for Travis and GitLab. If you create a pull request for that I am happy to review and merge.

**Comment by byrond** [comment]
@juampynr it looks like the Travis configuration uses a different Docker image: `wodby`, so I'm inclined to leave that one alone. That just leaves two instances of `RoboFile.php`:
- https://github.com/Lullabot/drupal8ci/blob/53c9e8e6e82b682479e26e30339e3cef19cf19fe/dist/github-actions/RoboFile.php
- https://github.com/Lullabot/drupal8ci/blob/e5bb2c2f659a1cb41307a8b0d3731a75bdd0b000/dist/gitlabci/RoboFile.php

Should they be updated or left as-is?

**Comment by juampynr** [comment]
Correct @byrond! I think that the Travis setup is not affected by this change.

As for the other two files, I have not tested it manually but those two files do not seem to require any changes as they don't refer any absolute paths to the root directory where the project is checked out.

**Pull request merged**
