### PR TITLE
Drupal 9 integration

### PR DESCRIPTION
**Pull request by fjgarlin**
Addresses: https://github.com/Lullabot/drupal8ci/issues/64

**Goal**: least amount of changes to make it work on a D9 project.

Summary of the changes:
* Modified `wget` line to allow URLs to contain `&` without breaking.
* Modified description on `dist/common/web/modules/custom/demo_module/src/DemoModuleExampleService.php` to pass coding standards validation.
* Removed `dist/common/web/modules/custom/demo_module/tests/src/ExistingSiteJavascript/ExistingSiteTest.php` as official Javascript testing on Drupal is different (classes should extend `Drupal\FunctionalJavascriptTests\WebDriverTestBase`)
* As it's Drupal 9, then only one `phpunit` configuration file only needed.
* Reduced dev dependencies to `core-dev` and the one needed for `behat`.
* _Travis_: Changing `trusty` to `xenial` as it contains `gd` and `zip` packages by default.
* _Travis_: Raising PHP and MariaDB versions to newer ones.
* _CircleCI_: Remove caching as it was failing.

Progress
- [x] Travis
- [x] CircleCI
- [ ] Github Actions
- [ ] Gitlab

### CODE REVIEW

**Comment by juampynr** [comment]
Thank you so much for updating these scripts @fjgarlin. I am keen on merging this pull request if it builds successfully for TravisCI and CircleCI. Let me know how you would like to handle it.

**Comment by fjgarlin** [comment]
It is building successfully for those two so far. See last commit with green tick on the PRs I've been testing on:
* TravisCI changes on D9: https://github.com/fjgarlin/d9-lagoon/pull/1 
* CircleCI changes on D9: https://github.com/fjgarlin/d9-lagoon/pull/2

Bear in mind that this is with Drupal 9. I haven't been testing these changes on Drupal 8 (end of life this year anyway).

I'm happy to open other PRs if I get to do Github actions or Gitlab integration, so I'm happy for you to merge this too.

**Comment by juampynr** [comment]
Thanks Fran!

Regarding compatibility, I think that we can either do it later or simply focus on Drupal 9.

I just realised that I might need to change the name of this repo since it mentions drupal 8.

**Comment by juampynr** [comment]
Worked! https://github.com/Lullabot/drupal9ci

GitHub takes care of redirections. This is great :-D

**Comment by fjgarlin** [comment]
Awesome!

**Pull request merged**
